name       : lollypop-portal
version    : 0.9.7
release    : 6
source     :
    - https://gitlab.gnome.org/gnumdk/lollypop-portal/uploads/42bd030f9c8391db93a335c6a23783bf/lollypop-portal-0.9.7.tar.xz : fef0d7b5a4065884582fef6e6e40ae781fe182063a07cfcc5d98a69602f4d57b
license    : GPL-3.0-only
component  : multimedia.audio
summary    : Lollypop flatpak portal (advanced features for Lollypop)
description: |
    Lollypop portal dbus service allow Lollypop to launch external commands (pa-cmd, kid3-cli, ...) through flatpak sandbox. This service is also used when running without sandbox.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(python3)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
