name       : lollypop-portal
version    : 0.9.1
release    : 1
source     :
    - https://github.com/gnumdk/lollypop-portal/archive/0.9.1.tar.gz : f0bfecc2c9bee3c7479084ca010f9c869d780388f8b28cf568605fcdcda1906b
license    : GPL-3.0
component  : multimedia.audio
summary    : Lollypop flatpak portal (advanced features for Lollypop)
description: |
    Lollypop portal dbus service allow Lollypop to launch external commands (pa-cmd, kid3-cli, ...) through flatpak sandbox. This service is also used when running without sandbox.
builddeps  : 
    - pkgconfig(gtk+-3.0)
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
